### PR TITLE
Update EmberCLI

### PR DESCRIPTION
**Pull request by mike183**
This PR primarily updates the version of EmberCLI to v3.2.0.

In addition it also does a few other things:

- Updates tests to the most current structure (using `qunit-dom` where possible)
- Removes usage of jQuery in tests
- Adds a `yarn.lock` file

### CODE REVIEW

**Comment by ryedeer** [comment]
Thank you for the PR! Actually, I almost forgot about this addon because I finished working on the project where it was used, so it became a bit aged :)

**Comment by mike183** [comment]
@ryedeer Thanks for merging! Any chance of cutting a new release containing these changes?

**Comment by ryedeer** [comment]
@mike183 Just published the updated version to npm!

**Comment by mike183** [comment]
Awesome, thank you! 🎉

**Pull request merged**
